// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: api/server/paymentinternal/paymentinternal.proto

package paymentinternal

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StoreUserBalanceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Balance *UserBalance `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
}

func (x *StoreUserBalanceRequest) Reset() {
	*x = StoreUserBalanceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_server_paymentinternal_paymentinternal_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreUserBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreUserBalanceRequest) ProtoMessage() {}

func (x *StoreUserBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_paymentinternal_paymentinternal_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreUserBalanceRequest.ProtoReflect.Descriptor instead.
func (*StoreUserBalanceRequest) Descriptor() ([]byte, []int) {
	return file_api_server_paymentinternal_paymentinternal_proto_rawDescGZIP(), []int{0}
}

func (x *StoreUserBalanceRequest) GetBalance() *UserBalance {
	if x != nil {
		return x.Balance
	}
	return nil
}

type StoreUserBalanceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID string `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
}

func (x *StoreUserBalanceResponse) Reset() {
	*x = StoreUserBalanceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_server_paymentinternal_paymentinternal_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreUserBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreUserBalanceResponse) ProtoMessage() {}

func (x *StoreUserBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_paymentinternal_paymentinternal_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreUserBalanceResponse.ProtoReflect.Descriptor instead.
func (*StoreUserBalanceResponse) Descriptor() ([]byte, []int) {
	return file_api_server_paymentinternal_paymentinternal_proto_rawDescGZIP(), []int{1}
}

func (x *StoreUserBalanceResponse) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type FindUserBalanceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID string `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
}

func (x *FindUserBalanceRequest) Reset() {
	*x = FindUserBalanceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_server_paymentinternal_paymentinternal_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindUserBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindUserBalanceRequest) ProtoMessage() {}

func (x *FindUserBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_paymentinternal_paymentinternal_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindUserBalanceRequest.ProtoReflect.Descriptor instead.
func (*FindUserBalanceRequest) Descriptor() ([]byte, []int) {
	return file_api_server_paymentinternal_paymentinternal_proto_rawDescGZIP(), []int{2}
}

func (x *FindUserBalanceRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type FindUserBalanceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Balance *UserBalance `protobuf:"bytes,1,opt,name=balance,proto3,oneof" json:"balance,omitempty"`
}

func (x *FindUserBalanceResponse) Reset() {
	*x = FindUserBalanceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_server_paymentinternal_paymentinternal_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindUserBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindUserBalanceResponse) ProtoMessage() {}

func (x *FindUserBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_paymentinternal_paymentinternal_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindUserBalanceResponse.ProtoReflect.Descriptor instead.
func (*FindUserBalanceResponse) Descriptor() ([]byte, []int) {
	return file_api_server_paymentinternal_paymentinternal_proto_rawDescGZIP(), []int{3}
}

func (x *FindUserBalanceResponse) GetBalance() *UserBalance {
	if x != nil {
		return x.Balance
	}
	return nil
}

type UserBalance struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID  string `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Balance int64  `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
}

func (x *UserBalance) Reset() {
	*x = UserBalance{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_server_paymentinternal_paymentinternal_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserBalance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBalance) ProtoMessage() {}

func (x *UserBalance) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_paymentinternal_paymentinternal_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBalance.ProtoReflect.Descriptor instead.
func (*UserBalance) Descriptor() ([]byte, []int) {
	return file_api_server_paymentinternal_paymentinternal_proto_rawDescGZIP(), []int{4}
}

func (x *UserBalance) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *UserBalance) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

var File_api_server_paymentinternal_paymentinternal_proto protoreflect.FileDescriptor

var file_api_server_paymentinternal_paymentinternal_proto_rawDesc = []byte{
	0x0a, 0x30, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x61, 0x79,
	0x6d, 0x65, 0x6e, 0x74, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x61, 0x79,
	0x6d, 0x65, 0x6e, 0x74, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x07, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x49, 0x0a, 0x17, 0x53,
	0x74, 0x6f, 0x72, 0x65, 0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e,
	0x74, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x07, 0x62,
	0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x22, 0x32, 0x0a, 0x18, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x55,
	0x73, 0x65, 0x72, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x22, 0x30, 0x0a, 0x16, 0x46, 0x69,
	0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x22, 0x5a, 0x0a, 0x17,
	0x46, 0x69, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e,
	0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x50, 0x61, 0x79, 0x6d, 0x65,
	0x6e, 0x74, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x48, 0x00,
	0x52, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0a, 0x0a, 0x08,
	0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x22, 0x3f, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72,
	0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12,
	0x18, 0x0a, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x32, 0xc7, 0x01, 0x0a, 0x16, 0x50, 0x61,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x57, 0x0a, 0x10, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x20, 0x2e, 0x50, 0x61, 0x79, 0x6d, 0x65,
	0x6e, 0x74, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x6c, 0x61,
	0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x50, 0x61, 0x79,
	0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x55, 0x73, 0x65, 0x72, 0x42, 0x61,
	0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x54, 0x0a,
	0x0f, 0x46, 0x69, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65,
	0x12, 0x1f, 0x2e, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x55,
	0x73, 0x65, 0x72, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x20, 0x2e, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x46, 0x69, 0x6e, 0x64,
	0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x14, 0x5a, 0x12, 0x2f, 0x2e, 0x3b, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e,
	0x74, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_api_server_paymentinternal_paymentinternal_proto_rawDescOnce sync.Once
	file_api_server_paymentinternal_paymentinternal_proto_rawDescData = file_api_server_paymentinternal_paymentinternal_proto_rawDesc
)

func file_api_server_paymentinternal_paymentinternal_proto_rawDescGZIP() []byte {
	file_api_server_paymentinternal_paymentinternal_proto_rawDescOnce.Do(func() {
		file_api_server_paymentinternal_paymentinternal_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_server_paymentinternal_paymentinternal_proto_rawDescData)
	})
	return file_api_server_paymentinternal_paymentinternal_proto_rawDescData
}

var file_api_server_paymentinternal_paymentinternal_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_server_paymentinternal_paymentinternal_proto_goTypes = []interface{}{
	(*StoreUserBalanceRequest)(nil),  // 0: Payment.StoreUserBalanceRequest
	(*StoreUserBalanceResponse)(nil), // 1: Payment.StoreUserBalanceResponse
	(*FindUserBalanceRequest)(nil),   // 2: Payment.FindUserBalanceRequest
	(*FindUserBalanceResponse)(nil),  // 3: Payment.FindUserBalanceResponse
	(*UserBalance)(nil),              // 4: Payment.UserBalance
}
var file_api_server_paymentinternal_paymentinternal_proto_depIdxs = []int32{
	4, // 0: Payment.StoreUserBalanceRequest.balance:type_name -> Payment.UserBalance
	4, // 1: Payment.FindUserBalanceResponse.balance:type_name -> Payment.UserBalance
	0, // 2: Payment.PaymentInternalService.StoreUserBalance:input_type -> Payment.StoreUserBalanceRequest
	2, // 3: Payment.PaymentInternalService.FindUserBalance:input_type -> Payment.FindUserBalanceRequest
	1, // 4: Payment.PaymentInternalService.StoreUserBalance:output_type -> Payment.StoreUserBalanceResponse
	3, // 5: Payment.PaymentInternalService.FindUserBalance:output_type -> Payment.FindUserBalanceResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_server_paymentinternal_paymentinternal_proto_init() }
func file_api_server_paymentinternal_paymentinternal_proto_init() {
	if File_api_server_paymentinternal_paymentinternal_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_server_paymentinternal_paymentinternal_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreUserBalanceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_server_paymentinternal_paymentinternal_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreUserBalanceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_server_paymentinternal_paymentinternal_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindUserBalanceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_server_paymentinternal_paymentinternal_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindUserBalanceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_server_paymentinternal_paymentinternal_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserBalance); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_server_paymentinternal_paymentinternal_proto_msgTypes[3].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_server_paymentinternal_paymentinternal_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_server_paymentinternal_paymentinternal_proto_goTypes,
		DependencyIndexes: file_api_server_paymentinternal_paymentinternal_proto_depIdxs,
		MessageInfos:      file_api_server_paymentinternal_paymentinternal_proto_msgTypes,
	}.Build()
	File_api_server_paymentinternal_paymentinternal_proto = out.File
	file_api_server_paymentinternal_paymentinternal_proto_rawDesc = nil
	file_api_server_paymentinternal_paymentinternal_proto_goTypes = nil
	file_api_server_paymentinternal_paymentinternal_proto_depIdxs = nil
}
