// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: api/server/paymentinternal/paymentinternal.proto

package paymentinternal

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PaymentInternalServiceClient is the client API for PaymentInternalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaymentInternalServiceClient interface {
	StoreUserBalance(ctx context.Context, in *StoreUserBalanceRequest, opts ...grpc.CallOption) (*StoreUserBalanceResponse, error)
	FindUserBalance(ctx context.Context, in *FindUserBalanceRequest, opts ...grpc.CallOption) (*FindUserBalanceResponse, error)
}

type paymentInternalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentInternalServiceClient(cc grpc.ClientConnInterface) PaymentInternalServiceClient {
	return &paymentInternalServiceClient{cc}
}

func (c *paymentInternalServiceClient) StoreUserBalance(ctx context.Context, in *StoreUserBalanceRequest, opts ...grpc.CallOption) (*StoreUserBalanceResponse, error) {
	out := new(StoreUserBalanceResponse)
	err := c.cc.Invoke(ctx, "/Payment.PaymentInternalService/StoreUserBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentInternalServiceClient) FindUserBalance(ctx context.Context, in *FindUserBalanceRequest, opts ...grpc.CallOption) (*FindUserBalanceResponse, error) {
	out := new(FindUserBalanceResponse)
	err := c.cc.Invoke(ctx, "/Payment.PaymentInternalService/FindUserBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentInternalServiceServer is the server API for PaymentInternalService service.
// All implementations must embed UnimplementedPaymentInternalServiceServer
// for forward compatibility
type PaymentInternalServiceServer interface {
	StoreUserBalance(context.Context, *StoreUserBalanceRequest) (*StoreUserBalanceResponse, error)
	FindUserBalance(context.Context, *FindUserBalanceRequest) (*FindUserBalanceResponse, error)
	mustEmbedUnimplementedPaymentInternalServiceServer()
}

// UnimplementedPaymentInternalServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPaymentInternalServiceServer struct {
}

func (UnimplementedPaymentInternalServiceServer) StoreUserBalance(context.Context, *StoreUserBalanceRequest) (*StoreUserBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoreUserBalance not implemented")
}
func (UnimplementedPaymentInternalServiceServer) FindUserBalance(context.Context, *FindUserBalanceRequest) (*FindUserBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindUserBalance not implemented")
}
func (UnimplementedPaymentInternalServiceServer) mustEmbedUnimplementedPaymentInternalServiceServer() {
}

// UnsafePaymentInternalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentInternalServiceServer will
// result in compilation errors.
type UnsafePaymentInternalServiceServer interface {
	mustEmbedUnimplementedPaymentInternalServiceServer()
}

func RegisterPaymentInternalServiceServer(s grpc.ServiceRegistrar, srv PaymentInternalServiceServer) {
	s.RegisterService(&PaymentInternalService_ServiceDesc, srv)
}

func _PaymentInternalService_StoreUserBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreUserBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentInternalServiceServer).StoreUserBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Payment.PaymentInternalService/StoreUserBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentInternalServiceServer).StoreUserBalance(ctx, req.(*StoreUserBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentInternalService_FindUserBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindUserBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentInternalServiceServer).FindUserBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Payment.PaymentInternalService/FindUserBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentInternalServiceServer).FindUserBalance(ctx, req.(*FindUserBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaymentInternalService_ServiceDesc is the grpc.ServiceDesc for PaymentInternalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaymentInternalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Payment.PaymentInternalService",
	HandlerType: (*PaymentInternalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StoreUserBalance",
			Handler:    _PaymentInternalService_StoreUserBalance_Handler,
		},
		{
			MethodName: "FindUserBalance",
			Handler:    _PaymentInternalService_FindUserBalance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/server/paymentinternal/paymentinternal.proto",
}
