// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: api/server/notificationinternal/notificationinternal.proto

package notificationinternal

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NotificationInternalServiceClient is the client API for NotificationInternalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotificationInternalServiceClient interface {
	FindNotificationsForUser(ctx context.Context, in *FindNotificationsForUserRequest, opts ...grpc.CallOption) (*FindNotificationsForUserResponse, error)
}

type notificationInternalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNotificationInternalServiceClient(cc grpc.ClientConnInterface) NotificationInternalServiceClient {
	return &notificationInternalServiceClient{cc}
}

func (c *notificationInternalServiceClient) FindNotificationsForUser(ctx context.Context, in *FindNotificationsForUserRequest, opts ...grpc.CallOption) (*FindNotificationsForUserResponse, error) {
	out := new(FindNotificationsForUserResponse)
	err := c.cc.Invoke(ctx, "/Notification.NotificationInternalService/FindNotificationsForUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotificationInternalServiceServer is the server API for NotificationInternalService service.
// All implementations must embed UnimplementedNotificationInternalServiceServer
// for forward compatibility
type NotificationInternalServiceServer interface {
	FindNotificationsForUser(context.Context, *FindNotificationsForUserRequest) (*FindNotificationsForUserResponse, error)
	mustEmbedUnimplementedNotificationInternalServiceServer()
}

// UnimplementedNotificationInternalServiceServer must be embedded to have forward compatible implementations.
type UnimplementedNotificationInternalServiceServer struct {
}

func (UnimplementedNotificationInternalServiceServer) FindNotificationsForUser(context.Context, *FindNotificationsForUserRequest) (*FindNotificationsForUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindNotificationsForUser not implemented")
}
func (UnimplementedNotificationInternalServiceServer) mustEmbedUnimplementedNotificationInternalServiceServer() {
}

// UnsafeNotificationInternalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotificationInternalServiceServer will
// result in compilation errors.
type UnsafeNotificationInternalServiceServer interface {
	mustEmbedUnimplementedNotificationInternalServiceServer()
}

func RegisterNotificationInternalServiceServer(s grpc.ServiceRegistrar, srv NotificationInternalServiceServer) {
	s.RegisterService(&NotificationInternalService_ServiceDesc, srv)
}

func _NotificationInternalService_FindNotificationsForUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindNotificationsForUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationInternalServiceServer).FindNotificationsForUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Notification.NotificationInternalService/FindNotificationsForUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationInternalServiceServer).FindNotificationsForUser(ctx, req.(*FindNotificationsForUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NotificationInternalService_ServiceDesc is the grpc.ServiceDesc for NotificationInternalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NotificationInternalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Notification.NotificationInternalService",
	HandlerType: (*NotificationInternalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindNotificationsForUser",
			Handler:    _NotificationInternalService_FindNotificationsForUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/server/notificationinternal/notificationinternal.proto",
}
