// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: api/server/orderinternal/orderinternal.proto

package orderinternal

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OrderInternalServiceClient is the client API for OrderInternalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderInternalServiceClient interface {
	CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error)
	FindOrder(ctx context.Context, in *FindOrderRequest, opts ...grpc.CallOption) (*FindOrderResponse, error)
}

type orderInternalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderInternalServiceClient(cc grpc.ClientConnInterface) OrderInternalServiceClient {
	return &orderInternalServiceClient{cc}
}

func (c *orderInternalServiceClient) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error) {
	out := new(CreateOrderResponse)
	err := c.cc.Invoke(ctx, "/Order.OrderInternalService/CreateOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderInternalServiceClient) FindOrder(ctx context.Context, in *FindOrderRequest, opts ...grpc.CallOption) (*FindOrderResponse, error) {
	out := new(FindOrderResponse)
	err := c.cc.Invoke(ctx, "/Order.OrderInternalService/FindOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderInternalServiceServer is the server API for OrderInternalService service.
// All implementations must embed UnimplementedOrderInternalServiceServer
// for forward compatibility
type OrderInternalServiceServer interface {
	CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error)
	FindOrder(context.Context, *FindOrderRequest) (*FindOrderResponse, error)
	mustEmbedUnimplementedOrderInternalServiceServer()
}

// UnimplementedOrderInternalServiceServer must be embedded to have forward compatible implementations.
type UnimplementedOrderInternalServiceServer struct {
}

func (UnimplementedOrderInternalServiceServer) CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrder not implemented")
}
func (UnimplementedOrderInternalServiceServer) FindOrder(context.Context, *FindOrderRequest) (*FindOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindOrder not implemented")
}
func (UnimplementedOrderInternalServiceServer) mustEmbedUnimplementedOrderInternalServiceServer() {}

// UnsafeOrderInternalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderInternalServiceServer will
// result in compilation errors.
type UnsafeOrderInternalServiceServer interface {
	mustEmbedUnimplementedOrderInternalServiceServer()
}

func RegisterOrderInternalServiceServer(s grpc.ServiceRegistrar, srv OrderInternalServiceServer) {
	s.RegisterService(&OrderInternalService_ServiceDesc, srv)
}

func _OrderInternalService_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderInternalServiceServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Order.OrderInternalService/CreateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderInternalServiceServer).CreateOrder(ctx, req.(*CreateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderInternalService_FindOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderInternalServiceServer).FindOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Order.OrderInternalService/FindOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderInternalServiceServer).FindOrder(ctx, req.(*FindOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderInternalService_ServiceDesc is the grpc.ServiceDesc for OrderInternalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderInternalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Order.OrderInternalService",
	HandlerType: (*OrderInternalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrder",
			Handler:    _OrderInternalService_CreateOrder_Handler,
		},
		{
			MethodName: "FindOrder",
			Handler:    _OrderInternalService_FindOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/server/orderinternal/orderinternal.proto",
}
